# Project settings

In [1]:
import os
from pathlib import Path

project_root = Path(os.getcwd()).parent.resolve()
Path(project_root).resolve()
os.chdir(project_root)

In [2]:
import pandas as pd
from ieee_cis_fraud_detection import config

2026-03-17 21:08:46.902 | INFO     | ieee_cis_fraud_detection.config:<module>:11 - PROJ_ROOT path is: /home/laenra/projects/ieee-cis-fraud-detection

# Read data

List transaction data

In [5]:
train_transaction_files= [
    os.path.join(
        config.INTERIM_DATA_DIR,
        'train_transaction_chunks',
        fn
    )
    for fn in os.listdir(os.path.join(config.INTERIM_DATA_DIR, 'train_transaction_chunks'))
]

identity_files= [
    os.path.join(
        config.INTERIM_DATA_DIR,
        'train_identity_chunks',
        fn
    )
    for fn in os.listdir(os.path.join(config.INTERIM_DATA_DIR, 'train_identity_chunks'))
]

print(f"Total number of train_transaction files: {len(train_transaction_files)}")
print(f"Total number of identity files: {len(identity_files)}")

Total number of train_transaction files: 60
Total number of identity files: 15

Feature importance

In [4]:
# Read feature importance data
import pandas as pd

feature_importance_df= pd.read_csv(
    os.path.join(
        config.INTERIM_DATA_DIR,
        "eda_catboost_feature_importances.csv",
    )
)

feature_importance_df

,feature_importance,feature_name,feature_importance_rank,cumulative_importances
0,6.971807,C14,1.0,6.971807
1,5.849631,C13,2.0,12.821439
2,4.454227,C1,3.0,17.275666
3,3.421978,TransactionAmt,4.0,20.697644
4,3.389769,V317,5.0,24.087413
...,...,...,...,...
372,0.000000,V335,373.0,100.000000
373,0.000000,V336,374.0,100.000000
374,0.000000,V337,375.0,100.000000
375,0.000000,V338,376.0,100.000000
376,0.000000,V339,377.0,100.000000

In [17]:
import pandas as pd
sample_transaction_data= pd.read_parquet(train_transaction_files[0])
sample_identity_data= pd.read_parquet(identity_files[0])
columns= sample_transaction_data.columns.to_list()

In [24]:
sample_identity_data.id_10.unique()

array([ nan,   0.,  -2.,  -6.,  -1.,  -5., -11.,  -8., -10., -36., -26.,
        -7.,  -4.,  -3., -13., -21., -31.,  -9., -19., -18., -51., -12.,
       -15., -39., -22., -34., -50., -24., -23., -25., -47.])

In [29]:
sample_identity_data

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
50000,3100498,-5.0,81437.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 63.0,24.0,1920x1080,match_status:2,T,F,T,F,desktop,Windows
50001,3100499,-5.0,61582.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,firefox 57.0,24.0,1360x768,match_status:2,T,F,T,T,desktop,Windows
50002,3100500,-5.0,120434.0,NaN,NaN,1.0,-9.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,2208x1242,match_status:1,T,F,T,F,mobile,iOS Device
50003,3100501,-5.0,28713.0,NaN,NaN,9.0,-34.0,NaN,NaN,NaN,...,mobile safari 10.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
50004,3100503,-5.0,244355.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,edge 16.0,24.0,2736x1824,match_status:2,T,F,T,T,desktop,Windows
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,3129262,0.0,132017.0,NaN,NaN,5.0,-100.0,NaN,NaN,NaN,...,chrome 63.0 for android,NaN,None,None,F,F,T,T,mobile,5011A Build/NRD90M
59996,3129270,-5.0,246928.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,chrome 63.0,NaN,None,None,F,F,T,T,desktop,None
59997,3129275,-5.0,88447.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 63.0,NaN,None,None,F,F,T,T,desktop,Windows
59998,3129276,-15.0,242233.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 63.0 for android,NaN,None,None,F,F,T,T,mobile,LG-K200 Build/MXB48T
59999,3129299,-5.0,110668.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,edge 16.0,NaN,None,None,F,F,T,T,desktop,Windows

In [28]:
sample_transaction_data.M1.unique()

array([None, 'T'], dtype=object)

# Model initiation